name: LinkChecker

on: push
# Add a top-level `if` to disable the workflow
if: ${{ false }}
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: '.link_config.json'
        use-verbose-mode: 'yes'
