name: Spell Check

on: [push, workflow_dispatch]
# Add a top-level `if` to disable the workflow
if: ${{ false }}
jobs:
  run:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Spell Check
      uses: crate-ci/typos@master
      with:
        config: .typos.toml
